"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import SiteHeader from "@/components/SiteHeader";

export default function LegalPage() {
  const router = useRouter();
  const [activeSection, setActiveSection] = useState("Health");

  function handleSectionChange(item) {
    setActiveSection(item);
    router.push(`/?section=${item.toLowerCase()}`);
  }

  return (
    <div id="legal" className="page-shell">
      <SiteHeader
        activePage="legal"
        activeSection={activeSection}
        onSectionChange={handleSectionChange}
        showSectionHomeLink
      />

      <main className="legal-page page-container">
        <div className="legal-content">
          <h1 className="legal-title">Legal Notice &amp; Editorial Standards</h1>
          <p className="legal-subtitle">Last updated: April 2026</p>

          <section className="legal-section">
            <h2 className="legal-section-heading">Nature of Content</h2>
            <p className="legal-body">
              ClearLens is an AI-assisted journalism platform. All articles published on this site are generated by artificial intelligence and are intended for informational purposes only. ClearLens does not employ human journalists and does not represent the editorial views of any individual, organization, or institution. Every article is clearly labeled as AI-generated content.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-heading">Accuracy and Verification</h2>
            <p className="legal-body">
              While ClearLens makes every effort to ground its reporting in credible, named sources, AI-generated content may contain factual errors, outdated information, or misattributed citations. ClearLens does not guarantee the accuracy, completeness, or timeliness of any article published on this platform. Readers are strongly encouraged to independently verify all claims before acting on any information presented here. ClearLens accepts no liability for decisions made based on content published on this platform.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-heading">Source Attribution</h2>
            <p className="legal-body">
              ClearLens attributes sources in good faith based on information available at the time of generation. Source citations are provided for reference and do not imply endorsement by the cited institution or publication. If you represent an organization that has been incorrectly cited, please contact us at <a href="mailto:legal@clearlens.ai">legal@clearlens.ai</a>.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-heading">Editorial Independence and Bias</h2>
            <p className="legal-body">
              ClearLens is designed to present information without political, ideological, or commercial bias. Every article is assigned an automated bias score based on language and framing analysis. This score is provided for transparency and does not constitute a guarantee of neutrality. No advertiser, sponsor, or third party influences the content generated on this platform.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-heading">Copyright and Reproduction</h2>
            <p className="legal-body">
              Articles generated by ClearLens are original AI-generated works. You may share links to ClearLens articles freely. Reproduction of full article text without attribution is not permitted. Images displayed on ClearLens are sourced from Unsplash and are used under the Unsplash License. Photographer credits are displayed with each image.
            </p>
          </section>

          <section className="legal-section">
            <h2 className="legal-section-heading">No Legal or Medical Advice</h2>
            <p className="legal-body">
              Nothing on ClearLens constitutes legal, medical, financial, or professional advice. Articles covering health, law, or financial topics are provided for general informational purposes only. Always consult a qualified professional before making decisions in these areas.
            </p>
          </section>

          <section className="legal-section legal-section-last">
            <h2 className="legal-section-heading">Contact</h2>
            <p className="legal-body">
              For corrections, legal inquiries, or source disputes: <a href="mailto:legal@clearlens.ai">legal@clearlens.ai</a>
              <br />
              For general inquiries: <a href="mailto:hello@clearlens.ai">hello@clearlens.ai</a>
            </p>
          </section>
        </div>
      </main>
    </div>
  );
}